--- 
:release_notes: initial release
:type: widget
:licenses: [1]

:dependencies: 
- :type: websdk
  :name: websdk
  :version: ">=2.1"
:name: app:as_flexflow
:tags: [ flex, photo, flash ]

:description: app:as_flexflow widget provides a coverflow-like graphic functionality
:version: 1.0.2
