--- 
:type: widget
:name: app:shadowbox
:version: 1.0.1
:dependencies: 
- :type: websdk
  :version: ">=2.1"
  :name: websdk
:tags: [ dialog ]
:licenses: [1]
:description: "app:shadowbox wraps the Shadowbox library useful for viewing media in a modal dialog"