--- 
:type: widget
# Tags should be a comma-separated list of identifiers, like: [happy, tasty, ajaxy]
:tags: [panel, layout]

:dependencies: 
- :type: websdk
  :name: websdk
  :version: ">=2.1"
:description: app:simple_panel widget
:name: app:simple_panel
:version: 1.0.1
:release_notes: initial release
:licenses: [6]

