--- 
:type: widget
:name: app:stopwatch
:version: 1.0
:dependencies: 
- :type: websdk
  :version: ">=2.1"
  :name: websdk
:tags: [ uicontrol ]
:licenses: [1]
:description: "app:stopwatch is a simple UI control for displaying and controlling a stop watch"