--- 
:type: widget
:name: app:template
:version: 1.0
:dependencies: 
- :type: websdk
  :version: ">=2.1"
  :name: websdk
:tags: [ layout ]
:description: "app:template is a layout component for loading content based on a template"