--- 
:type: widget
:name: app:download
:version: 1.0
:dependencies: 
- :type: websdk
  :version: ">=2.1"
  :name: websdk
:tags: [ ]
:description: "app:download is a simple utility for doing dynamic downloads using a remote service"
