--- 
:type: websdk
:name: websdk
:version: 3.0.0
:dependencies: 
- :type: runtime
  :name: runtime
  :version: ">=2.0"
- :type: widget
  :name: app:calendar
  :version: ">=1.0"
- :type: widget
  :name: app:chart
  :version: ">=1.0"
- :type: widget
  :name: app:content
  :version: ">=1.0"
- :type: widget
  :name: app:datatable
  :version: ">=1.0"
- :type: widget
  :name: app:editinplace
  :version: ">=1.0"
- :type: widget
  :name: app:folder
  :version: ">=1.0"
- :type: widget
  :name: app:http
  :version: ">=1.0"
- :type: widget
  :name: app:if
  :version: ">=1.0"
- :type: widget
  :name: app:iterator
  :version: ">=1.0.1"
- :type: widget
  :name: app:message
  :version: ">=1.0"
- :type: widget
  :name: app:script
  :version: ">=1.0"
- :type: widget
  :name: app:statemachine
  :version: ">=1.0"
- :type: widget
  :name: app:upload
  :version: ">=1.0"
