--- 
:type: websdk
:name: websdk
:version: 2.1.1
:dependencies: 
- :type: widget
  :name: app:box
  :version: ">=1.0"
- :type: widget
  :name: app:button
  :version: ">=1.0"
- :type: widget
  :name: app:calendar
  :version: ">=1.0"
- :type: widget
  :name: app:chart
  :version: ">=1.0"
- :type: widget
  :name: app:content
  :version: ">=1.0"
- :type: widget
  :name: app:datatable
  :version: ">=1.0"
- :type: widget
  :name: app:download
  :version: ">=1.0"
- :type: widget
  :name: app:editinplace
  :version: ">=1.0"
- :type: widget
  :name: app:folder
  :version: ">=1.0"
- :type: widget
  :name: app:http
  :version: ">=1.0"
- :type: widget
  :name: app:if
  :version: ">=1.0"
- :type: widget
  :name: app:iterator
  :version: ">=1.0.1"
- :type: widget
  :name: app:message
  :version: ">=1.0"
- :type: widget
  :name: app:modaldialog
  :version: ">=1.0"
- :type: widget
  :name: app:pagination
  :version: ">=1.0"
- :type: widget
  :name: app:panel
  :version: ">=1.0"
- :type: widget
  :name: app:progressbar
  :version: ">=1.0"
- :type: widget
  :name: app:script
  :version: ">=1.0"
- :type: widget
  :name: app:search
  :version: ">=1.0"
- :type: widget
  :name: app:statemachine
  :version: ">=1.0"
- :type: widget
  :name: app:template
  :version: ">=1.0"
- :type: widget
  :name: app:tooltip
  :version: ">=1.0"
- :type: widget
  :name: app:upload
  :version: ">=1.0"
- :type: widget
  :name: app:validation
  :version: ">=1.0"
- :type: widget
  :name: app:yui_map
  :version: ">=1.0"
