#!/bin/sh
#
# This file is part of Appcelerator.
#
# Copyright (C) 2006-2008 by Appcelerator, Inc. All Rights Reserved.
# For more information, please visit http://www.appcelerator.org
#
# Appcelerator is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


#
# we need to check and see if we're in pre-flight mode
#
if [ $UID -eq 0 ]
then
    if [ "$1" == "--postflight--" ]
    then
         echo "mkdir -p /Library/Appcelerator/releases" >> /tmp/appcelerator_installer.log
         mkdir -p /Library/Appcelerator/releases
         
         echo "mkdir -p /Library/Appcelerator/updates" >> /tmp/appcelerator_installer.log
         mkdir -p /Library/Appcelerator/updates

         echo "chown -R root:admin /Library/Appcelerator" >> /tmp/appcelerator_installer.log
         chown -R root:admin /Library/Appcelerator

         echo "chown -R root:admin /usr/bin/appcelerator" >> /tmp/appcelerator_installer.log
         chown -R root:admin /usr/bin/appcelerator

         echo "chmod -R 0777 /Library/Appcelerator/releases" >> /tmp/appcelerator_installer.log
         chmod -R 0777 /Library/Appcelerator/releases

         echo "chmod -R 0777 /Library/Appcelerator/updates" >> /tmp/appcelerator_installer.log
         chmod -R 0777 /Library/Appcelerator/updates

         echo "chmod -R 0666 /Library/Appcelerator/build.yml" >> /tmp/appcelerator_installer.log
         chmod -R 0666 /Library/Appcelerator/build.yml

         echo "chmod +x /Library/Appcelerator/appcelerator" >> /tmp/appcelerator_installer.log
         chmod +x /Library/Appcelerator/appcelerator

         echo "ln -fs /Library/Appcelerator/appcelerator /usr/bin/app" >> /tmp/appcelerator_installer.log
         ln -fs /Library/Appcelerator/appcelerator /usr/bin/app

         echo "chmod +x /usr/bin/app" >> /tmp/appcelerator_installer.log
         chmod +x /usr/bin/app

         echo "/usr/bin/app" >> /tmp/appcelerator_installer.log
         /usr/bin/app --install 2>/dev/null

         echo "open http://www.appcelerator.org" >> /tmp/appcelerator_installer.log
         open "http://www.appcelerator.org"

         echo "exiting successfully!" >> /tmp/appcelerator_installer.log
         exit 0
    fi 
fi

/Library/Appcelerator/appcelerator $*
exit $?
