#!/bin/sh
#
# This file is part of Appcelerator.
#
# Copyright (C) 2006-2008 by Appcelerator, Inc. All Rights Reserved.
# For more information, please visit http://www.appcelerator.org
#
# Appcelerator is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#


#
# we need to check and see if we're in pre-flight mode
#
if [ $UID -eq 0 ]
then
    if [ "$1" == "--postflight--" ]
    then
       # check to do the postflight install process for the macosx installer
         mkdir -p /Library/Appcelerator/releases
         mkdir -p /Library/Appcelerator/updates
         chown -R root:admin /Library/Appcelerator
         chown -R root:admin /usr/bin/appcelerator
         chmod -R 0777 /Library/Appcelerator/releases
         chmod -R 0777 /Library/Appcelerator/updates
         chmod +x /Library/Appcelerator/appcelerator
         ln -fs /Library/Appcelerator/appcelerator /usr/bin/app
         chmod +x /usr/bin/app
         /usr/bin/app
#         open "http://127.0.0.1:9080"
         open "http://www.appcelerator.org"
         exit 0
    fi 
fi

/Library/Appcelerator/appcelerator $*
exit $?
