--- 
:type: widget
:name: app:modalbox
:version: 1.0
:dependencies: 
- :type: websdk
  :version: ">=2.1"
  :name: websdk
:tags: [ dialog ]
:licenses: [1]
:description: "app:modalbox is a UI control for displaying a modal dialog box"
