#
# This file is part of Appcelerator.
#
# Copyright (c) 2006-2008, Appcelerator, Inc.
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
# 
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
# 
#     * Redistributions in binary form must reproduce the above copyright notice,
#       this list of conditions and the following disclaimer in the documentation
#       and/or other materials provided with the distribution.
# 
#     * Neither the name of Appcelerator, Inc. nor the names of its
#       contributors may be used to endorse or promote products derived from this
#       software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

#
# theme Rakefile
#

require 'rake'
require 'fileutils'
require 'zip/zip'
require 'yaml'
require 'find'
require 'pathname'

NAME = 'iphone_green'
ZIPFILE = File.expand_path "#{NAME}.zip"

desc 'default build which makes the theme'
task :default => [:zip] do
end

desc 'zip up the theme'
task :zip do
  build = YAML::load_file File.expand_path("#{File.dirname(__FILE__)}/build.yml")
  if build[:licenses].nil? or build[:licenses].empty?
    STDERR.puts "Before you can build the theme, you need to set the licensing type."
    STDERR.puts "Please see LICENSING.readme file for details or visit the documentation"
    STDERR.puts "for more information."
    exit 1
  end
  src_dir = File.expand_path "#{File.dirname(__FILE__)}"
  FileUtils.rm_r ZIPFILE if File.exists? ZIPFILE
  Zip::ZipFile.open(ZIPFILE, Zip::ZipFile::CREATE) do |zipfile|
    Find.find(src_dir) do |path|
        pathname = Pathname.new(path)
        next if path.include? '.svn' or path.include? 'Rakefile' or path.include? 'LICENSING.readme'
        if pathname.file?
          filename = pathname.relative_path_from(Pathname.new(src_dir))
          if path.include? "#{NAME}.js"
            zipfile.get_output_stream(filename) do |f|
              c = File.read(src_dir+'/'+filename)
              f.puts c.gsub('__VERSION__',build[:version].to_s)
            end
          else
            zipfile.add(filename,src_dir+'/'+filename)
          end
        end
    end
  end
end

desc 'install the theme'
task :install => [:zip] do
  system "appcelerator install:theme #{ZIPFILE}"
end

desc 'release the theme'
task :release => [:zip] do
  system "appcelerator release:theme #{ZIPFILE}"
end


