#
# This file is part of Appcelerator.
#
# Copyright (C) 2006-2008 by Appcelerator, Inc. All Rights Reserved.
# For more information, please visit http://www.appcelerator.org
#
# Appcelerator is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

BUILD_DIR = "#{File.dirname(__FILE__)}" 
require File.expand_path("#{BUILD_DIR}/../../build.rb")
build_config = load_config(BUILD_DIR)

desc 'default google-appengine-python build'
task :default do

  FileUtils.mkdir_p "#{STAGE_DIR}"
  zipfile = "#{STAGE_DIR}/service_pyappengine_#{build_config[:version]}.zip"
  FileUtils.rm_rf zipfile
  
  src_dir = "#{BUILD_DIR}/src"
  lib_dir = "#{BUILD_DIR}/lib"
  
  Zip::ZipFile.open(zipfile, Zip::ZipFile::CREATE) do |zipfile|
    
    dofiles(src_dir) do |f|
      filename = f.to_s
      next if File.basename(filename[0,1]) == '.'
      zipfile.add("project/#{filename}","#{src_dir}/#{filename}")
    end
    
    dofiles(lib_dir) do |f|
      filename = f.to_s
      next if File.basename(filename[0,1]) == '.'
      zipfile.add("project/#{filename}","#{lib_dir}/#{filename}")
    end
    
    Dir["#{BUILD_DIR}/installer/plugins/*.rb"].each do |fpath|
      filename = File.basename(fpath)
      next if filename[0,1] == '.'
      zipfile.add("plugins/#{filename}",fpath)
    end

    zipfile.add('install.rb', "#{BUILD_DIR}/installer/install.rb")
    zipfile.add('build.yml',"#{BUILD_DIR}/build.yml")
  end
end

