{
	"suites":
	[
		{script:"plugins/add_remove.js",html:"plugins/add_remove.html"},
		{script:"plugins/pubsub.js"},
		{script:"plugins/after.js"},
		{script:"controls/iterator.js",html:"controls/iterator.html",timeout:'5s'}
	]
}