--- 
:release_notes: initial release
:type: widget
:licenses: [6]

:dependencies: 
- :type: websdk
  :name: websdk
  :version: ">=2.1"
:name: app:accordion
:tags: [ layout, uicontrol ]

:description: app:accordion widget provides horizontal or vertical accordions by implementing http://www.stickmanlabs.com/accordion
:version: 1.0.2
