--- 
:type: widget
:name: app:combobox
:version: 1.0
:dependencies: 
- :type: websdk
  :version: ">=2.1"
  :name: websdk
:tags: [ uicontrol ]
:description: "app:combobox is a nicer looking control for doing combo boxes as an alternative to HTML selects"
