--- 
:type: widget
:release_notes: initial release
:dependencies: 
- :type: websdk
  :name: websdk
  :version: ">=2.1"
:name: app:graphical_music_player
:licenses: [1]

:description: app:graphical_music_player widget
:tags: [ audio, mp3, flash ]

:version: 1.0
