#
# This file is part of Appcelerator.
#
# Copyright (C) 2006-2008 by Appcelerator, Inc. All Rights Reserved.
# For more information, please visit http://www.appcelerator.org
#
# Appcelerator is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

BUILD_DIR = "#{File.dirname(__FILE__)}" 
require File.expand_path("#{BUILD_DIR}/../../build.rb")
build_config = load_config(BUILD_DIR)

desc 'default build'
task :default do

  FileUtils.mkdir_p "#{STAGE_DIR}"
  zipfile = "#{STAGE_DIR}/service_php_#{build_config[:version]}.zip"
  FileUtils.rm_rf zipfile

  Zip::ZipFile.open(zipfile, Zip::ZipFile::CREATE) do |zipfile|
    dofiles("#{BUILD_DIR}/src") do |f|
      filename = f.to_s
      if not filename == '.'
        zipfile.add(filename,"#{BUILD_DIR}/src/#{filename}")
      end
    end
    zipfile.add('install.rb',"#{BUILD_DIR}/installer/install.rb")
    zipfile.add('appcelerator.xml',"#{BUILD_DIR}/installer/appcelerator.xml")
    zipfile.add('build.yml',"#{BUILD_DIR}/build.yml")
    zipfile.add('test_service.php',"#{BUILD_DIR}/installer/test_service.php")
  end
end
