#
# This file is part of Appcelerator.
#
# Copyright 2006-2008 Appcelerator, Inc.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
BUILD_DIR = File.expand_path(File.dirname(__FILE__))
require File.join(BUILD_DIR, '..', 'build', 'build.rb')

SERVICES_DIR = File.join(BUILD_DIR, 'services')
BEHAVIORS_DIR = File.join(BUILD_DIR, 'behaviors')
CONTROLS_DIR = File.join(BUILD_DIR, 'controls')
LAYOUTS_DIR = File.join(BUILD_DIR, 'layouts')


task :default => [:all] do
end

task :cleanup do
	Dir["**/*.zip"].each do |zip|
		FileUtils.rm_rf zip
   end
end

task :all => %w(widget:all layout:all behavior:all control:all theme:all service:all websdk:all installer:all plugin:all) do
end

namespace :service do
  discover_rakefiles(:service, SERVICES_DIR)
end

namespace :behavior do
  discover_rakefiles(:behavior, BEHAVIORS_DIR)
end

namespace :control do
  discover_rakefiles(:control, CONTROLS_DIR)
end

namespace :layout do
  discover_rakefiles(:layout, LAYOUTS_DIR)
end


namespace :theme do
  
  task :all do 
    FileUtils.cd(File.expand_path("#{BUILD_DIR}/themes")) do |d|
      call_rake " all"
    end
  end

end

namespace :installer do
  
  task :all do 
    FileUtils.cd(File.expand_path("#{BUILD_DIR}/runtime")) do |d|
      call_rake " all"
    end
  end

  task :win32 do
    FileUtils.cd("#{BUILD_DIR}/runtime") do |d|
      call_rake " win32"
    end
  end

  task :unix do
    FileUtils.cd("#{BUILD_DIR}/runtime") do |d|
      call_rake " unix"
    end
  end

  task :osx do
    FileUtils.cd("#{BUILD_DIR}/runtime") do |d|
      call_rake " osx"
    end
  end

  task :update do
    FileUtils.cd("#{BUILD_DIR}/runtime") do |d|
      call_rake " update"
    end
  end
    
end

namespace :websdk do
  desc "Build the websdk"
  task :all do
    FileUtils.cd("#{BUILD_DIR}/websdk") do |d|
      call_rake "test" # test depends on default
    end
  end
  
  task :test do
    FileUtils.cd("#{BUILD_DIR}/websdk") do |d|
     call_rake " test"
    end
  end
  
  desc "Run the default set of tests (requires JAVA)"
  task :test => 'test:default'
  namespace :test do
    task :default do 
        FileUtils.cd("#{BUILD_DIR}/websdk") do |d|
          call_rake " test"
        end
    end
      
    task :webunit do 
      FileUtils.cd("#{BUILD_DIR}/websdk") do |d|
        call_rake " test"
      end
    end
    
    namespace :selenium do 
      task :start do 
        FileUtils.cd("#{BUILD_DIR}/websdk") do |d|
          call_rake " selenium:start"
        end
      end
      
      task :stop do 
        FileUtils.cd("#{BUILD_DIR}/websdk") do |d|
          call_rake " selenium:stop"
        end
      end
      
      task :all do 
        FileUtils.cd("#{BUILD_DIR}/websdk") do |d|
          call_rake " selenium:all"
        end
      end
      
      task :firefox do 
        FileUtils.cd("#{BUILD_DIR}/websdk") do |d|
          call_rake " selenium:firefox"
        end
      end
      
      task :safari do 
        FileUtils.cd("#{BUILD_DIR}/websdk") do |d|
          call_rake " selenium:safari"
        end
      end
      
      task :ie do 
        FileUtils.cd("#{BUILD_DIR}/websdk") do |d|
          call_rake " selenium:ie"
        end
      end
    end
    
    namespace :webrick do 
      task :start do 
        FileUtils.cd("#{BUILD_DIR}/websdk") do |d|
          call_rake " webrick:start"
        end
      end
      
      task :stop do 
        FileUtils.cd("#{BUILD_DIR}/websdk") do |d|
          call_rake " webrick:stop"
        end
      end
    end
  end
end

namespace :widget do
  
  task :all do
    FileUtils.cd("#{BUILD_DIR}/widgets") do |d|
      call_rake ""
    end
  end

end

#
# this is a nolan special
#
namespace :release do
  task :all do
    server = ENV['UPDATESITE'] || ENV['SERVER'] || 'http://updatesite.appcelerator.org'
    puts "==> releasing all widgets"
    system "app release #{STAGE_DIR}/all_widgets.zip --server=#{server}"
    puts "==> releasing websdk"
    system "app release #{Dir.glob(STAGE_DIR + '/websdk_*.zip').first} --server=#{server}"
    puts "==> releasing installer_update"
    system "app release #{Dir.glob(STAGE_DIR + '/installer_update_*.zip').first} --server=#{server}"

    %w(service installer plugin layout control behavior theme).each do |type|
      Dir.glob("#{STAGE_DIR}/#{type}_*.zip").each do |name|
        puts "==> releasing #{File.basename(name)}"
        system "app release #{name} --server=#{server}"
      end
    end
  end
end

