#
# This file is part of Appcelerator.
#
# Copyright (C) 2006-2008 by Appcelerator, Inc. All Rights Reserved.
# For more information, please visit http://www.appcelerator.org
#
# Appcelerator is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
BUILD_DIR = File.dirname(__FILE__)
require File.expand_path("#{BUILD_DIR}/build.rb")

task :default => [:all] do
end

task :all => %w(widget:all service:all websdk:all installer:all plugin:all) do
end

namespace :installer do
  
  task :all do 
    FileUtils.cd(File.expand_path("#{BUILD_DIR}/runtime")) do |d|
      call_rake " all"
    end
  end

  task :win32 do
    FileUtils.cd("#{BUILD_DIR}/runtime") do |d|
      call_rake " win32"
    end
  end

  task :unix do
    FileUtils.cd("#{BUILD_DIR}/runtime") do |d|
      call_rake " unix"
    end
  end

  task :osx do
    FileUtils.cd("#{BUILD_DIR}/runtime") do |d|
      call_rake " osx"
    end
  end

  task :update do
    FileUtils.cd("#{BUILD_DIR}/runtime") do |d|
      call_rake " update"
    end
  end
    
end

namespace :websdk do
  desc "Build the websdk"
  task :all do
    FileUtils.cd("#{BUILD_DIR}/websdk") do |d|
      call_rake ""
    end
  end
  
  # task :test do
  #   FileUtils.cd("#{BUILD_DIR}/websdk") do |d|
  #     call_rake " test"
  #   end
  # end
  
  desc "Run the default set of tests (requires JAVA)"
  task :test => 'test:default'
  namespace :test do
    task :default do 
        FileUtils.cd("#{BUILD_DIR}/websdk") do |d|
          call_rake " test"
        end
    end
      
    task :webunit do 
      FileUtils.cd("#{BUILD_DIR}/websdk") do |d|
        call_rake " test"
      end
    end
    
    namespace :selenium do 
      task :start do 
        FileUtils.cd("#{BUILD_DIR}/websdk") do |d|
          call_rake " selenium:start"
        end
      end
      
      task :stop do 
        FileUtils.cd("#{BUILD_DIR}/websdk") do |d|
          call_rake " selenium:stop"
        end
      end
      
      task :all do 
        FileUtils.cd("#{BUILD_DIR}/websdk") do |d|
          call_rake " selenium:stop"
        end
      end
      
      task :firefox do 
        FileUtils.cd("#{BUILD_DIR}/websdk") do |d|
          call_rake " selenium:firefox"
        end
      end
      
      task :safari do 
        FileUtils.cd("#{BUILD_DIR}/websdk") do |d|
          call_rake " selenium:safari"
        end
      end
      
      task :ie do 
        FileUtils.cd("#{BUILD_DIR}/websdk") do |d|
          call_rake " selenium:ie"
        end
      end
    end
    
    namespace :webrick do 
      task :start do 
        FileUtils.cd("#{BUILD_DIR}/websdk") do |d|
          call_rake " webrick:start"
        end
      end
      
      task :stop do 
        FileUtils.cd("#{BUILD_DIR}/websdk") do |d|
          call_rake " webrick:stop"
        end
      end
    end
  end
end

namespace :widget do
  
  task :all do
    FileUtils.cd("#{BUILD_DIR}/widgets") do |d|
      call_rake ""
    end
  end

end

namespace :service do
  
  task :all do
    FileUtils.cd("#{BUILD_DIR}/services") do |d|
      call_rake " all"
    end
  end

  task :java do
    FileUtils.cd("#{BUILD_DIR}/services") do |d|
      call_rake " java"
    end
  end

  task :python do
    FileUtils.cd("#{BUILD_DIR}/services") do |d|
      call_rake " python"
    end
  end

  task :appengine do
    FileUtils.cd("#{BUILD_DIR}/services") do |d|
      call_rake " appengine"
    end
  end

  task :dotnet do
    FileUtils.cd("#{BUILD_DIR}/services") do |d|
      call_rake " dotnet"
    end
  end

  task :ruby do
    FileUtils.cd("#{BUILD_DIR}/services") do |d|
      call_rake " ruby"
    end
  end

  task :perl do
    FileUtils.cd("#{BUILD_DIR}/services") do |d|
      call_rake " perl"
    end
  end

  task :php do
    FileUtils.cd("#{BUILD_DIR}/services") do |d|
      call_rake " php"
    end
  end

  task :zend do
    FileUtils.cd("#{BUILD_DIR}/services") do |d|
      call_rake " zend"
    end
  end

  task :merb do
    FileUtils.cd("#{BUILD_DIR}/services") do |d|
      call_rake " merb"
    end
  end

end

namespace :plugin do
  task :all do
    FileUtils.cd("#{BUILD_DIR}/plugins") do |d|
      call_rake ""
    end
  end

  task :java do
    FileUtils.cd("#{BUILD_DIR}/plugins") do |d|
      call_rake " java:all"
    end
  end

  task :java_spring do
    FileUtils.cd("#{BUILD_DIR}/plugins") do |d|
      call_rake " java:spring"
    end
  end
end


#
# this is a nolan special
#
namespace :release do
  task :all do
    server = ENV['SERVER'] || 'http://updatesite.appcelerator.org'
    puts "==> releasing all widgets"
    system "app release #{STAGE_DIR}/all_widgets.zip --server=#{server}"
    puts "==> releasing websdk"
    system "app release #{Dir.glob(STAGE_DIR + '/websdk_*.zip').first} --server=#{server}"
    puts "==> releasing installer_update"
    system "app release #{Dir.glob(STAGE_DIR + '/installer_update_*.zip').first} --server=#{server}"
    Dir.glob(STAGE_DIR+'/service_*.zip').each do |name|
      puts "==> releasing #{File.basename(name)}"
      system "app release #{name} --server=#{server}"
    end
    Dir.glob(STAGE_DIR+'/installer_*.zip').each do |name|
      puts "==> releasing #{File.basename(name)}"
      system "app release #{name} --server=#{server}"
    end
    Dir.glob(STAGE_DIR+'/plugin_*.zip').each do |name|
      puts "==> releasing #{File.basename(name)}"
      system "app release #{name} --server=#{server}"
    end
  end
end
