#
# This file is part of Appcelerator.
#
# Copyright 2006-2008 Appcelerator, Inc.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#

#
# Widget Rakefile
#

require 'rake'
require 'fileutils'
require 'zip/zip'
require 'yaml'
require 'find'
require 'pathname'

NAME = 'app_editinplace'
ZIPFILE = File.expand_path "#{NAME}.zip"

desc 'default build which makes the widget'
task :default => [:zip] do

end

desc 'zip up the widget'
task :zip do
  build = YAML::load_file File.expand_path("#{File.dirname(__FILE__)}/build.yml")
  if build[:licenses].nil? or build[:licenses].empty?
    STDERR.puts "Before you can build the widget, you need to set the licensing type."
    STDERR.puts "Please see LICENSING.readme file for details or visit the documentation"
    STDERR.puts "for more information."
    exit 1
  end
  src_dir = File.expand_path "#{File.dirname(__FILE__)}/src"
  FileUtils.rm_r ZIPFILE if File.exists? ZIPFILE
  Zip::ZipFile.open(ZIPFILE, Zip::ZipFile::CREATE) do |zipfile|
    Find.find(src_dir) do |path|
        pathname = Pathname.new(path)
        if not path.include? '.svn' and pathname.file?
          filename = pathname.relative_path_from(Pathname.new(src_dir))
          if path.include? "#{NAME}.js"
            zipfile.get_output_stream(filename) do |f|
              c = File.read(src_dir+'/'+filename)
              f.puts c.gsub('__VERSION__',build[:version].to_s)
            end
          else
            zipfile.add(filename,src_dir+'/'+filename)
          end
        end
    end
    zipfile.add('build.yml','build.yml')
  end
end

desc 'install the widget'
task :install => [:zip] do
  system "appcelerator install:widget #{ZIPFILE}"
end

desc 'release the widget'
task :release => [:zip] do
  system "appcelerator release:widget #{ZIPFILE}"
end


