--- 
:type: widget
:name: app:yui_map
:version: 1.0.1
:dependencies: 
- :type: websdk
  :version: ">=2.1"
  :name: websdk
:tags: [ upload, maps, yui ]
:licenses: [6]
:description: "app:yui_map is a Yahoo! based map UI control which supports dynamic mapping from messages"
