--- 
:type: widget
:name: app:widget
:version: 1.0
:dependencies: 
- :type: websdk
  :version: ">=2.1"
  :name: websdk
:tags: [ ]
:licenses: [6]
:description: "app:widget is a meta-widget which allows you to dynamically create a widget inline in your code"