#
# This file is part of Appcelerator.
#
# Copyright 2006-2008 Appcelerator, Inc.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
require File.expand_path("#{File.dirname(__FILE__)}/../build.rb")

def build_plugin(name)
  FileUtils.cd(name) do |dir|
		puts "==> Building #{dir}"
		call_rake
	  fn = "#{dir}.zip"
		if File.exists?(fn)
			FileUtils.cp fn,"#{STAGE_DIR}/plugin_#{fn}"
			FileUtils.rm_rf fn
		end
  end
end

task :all => [:default] do
end

task :default do
	Dir["*"].each do |dir|
		next unless File.directory?(dir)
		build_plugin File.basename(dir)
   end
end

namespace :java do
  task :all do
  	Dir["*"].each do |dir|
  		next unless File.directory?(dir)
  		name = File.basename(dir)
  		build_plugin name if name =~ /^java_/
     end
  end
  task :spring do
    build_plugin 'java_spring'
  end
end


