#
# This file is part of Appcelerator.
#
# Copyright (C) 2006-2008 by Appcelerator, Inc. All Rights Reserved.
# For more information, please visit http://www.appcelerator.org
#
# Appcelerator is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
require File.expand_path("#{File.dirname(__FILE__)}/../build.rb")

def build_plugin(name)
  FileUtils.cd(name) do |dir|
		puts "==> Building #{dir}"
		call_rake
	  fn = "#{dir}.zip"
		if File.exists?(fn)
			FileUtils.cp fn,"#{STAGE_DIR}/plugin_#{fn}"
			FileUtils.rm_rf fn
		end
  end
end

task :all => [:default] do
end

task :default do
	Dir["*"].each do |dir|
		next unless File.directory?(dir)
		build_plugin File.basename(dir)
   end
end

namespace :java do
  task :all do
  	Dir["*"].each do |dir|
  		next unless File.directory?(dir)
  		name = File.basename(dir)
  		build_plugin name if name =~ /^java_/
     end
  end
  task :spring do
    build_plugin 'java_spring'
  end
end


