#
#
# This file is part of Appcelerator.
#
# Copyright (c) 2006-2008, Appcelerator, Inc.
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
# 
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
# 
#     * Redistributions in binary form must reproduce the above copyright notice,
#       this list of conditions and the following disclaimer in the documentation
#       and/or other materials provided with the distribution.
# 
#     * Neither the name of Appcelerator, Inc. nor the names of its
#       contributors may be used to endorse or promote products derived from this
#       software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
BUILD_DIR = File.dirname(__FILE__)
require File.expand_path("#{BUILD_DIR}/../build.rb")

desc 'build all themes'
task :all => [:default] do
end

task :default => [:stage] do
  
  theme_dir = "#{STAGE_DIR}"
  
  themes = []

  Dir["#{BUILD_DIR}/*"].each do |typedir|
    next unless File.directory?(typedir)
    type = File.basename(typedir)
    Dir["#{BUILD_DIR}/#{type}/*"].each do |dir|
      next unless File.directory?(dir)
      name = File.basename(dir)
      Dir["#{BUILD_DIR}/#{type}/#{name}/*"].each do |themedir|
        next unless File.directory?(themedir)
        themename = File.basename(themedir)
        themes << {:name=>themename,:dir=>themedir,:filename=>"theme_#{name}_#{themename}.zip"}
      end
    end
  end
  
  themes.uniq.each do |entry|
    FileUtils.cd(entry[:dir]) do |dir|
      $stderr.puts "!! Invalid control theme - no Rakefile found in #{dir}" unless File.exists? "#{dir}/Rakefile"
      next unless File.exists? "#{dir}/Rakefile"
      puts entry[:filename]
      call_rake
      FileUtils.cp_r "#{entry[:name]}.zip", "#{theme_dir}/#{entry[:filename]}"
    end
  end
  
  FileUtils.rm_rf "#{STAGE_DIR}/all_themes.zip"
  
  Zip::ZipFile.open("#{STAGE_DIR}/all_themes.zip", Zip::ZipFile::CREATE) do |zipfile|
    dofiles("#{STAGE_DIR}") do |f|
      filename = f.to_s
      next unless File.extname(filename)=='.zip'
      next if filename == '.'
      zipfile.add(filename,"#{STAGE_DIR}/#{filename}")
    end
	 zipfile.get_output_stream('build.yml') do |o|
	   c = {:name=>'allthemes',:type=>'allthemes',:version=>1.0}	
	   o.puts c.to_yaml
    end
  end
  
  themes.each do |name|
    FileUtils.rm_rf "#{BUILD_DIR}/#{name}/#{name}.zip"
  end
  
end
