# This file is part of Appcelerator.
#
# Copyright (C) 2006-2008 by Appcelerator, Inc. All Rights Reserved.
# For more information, please visit http://www.appcelerator.org
#
# Appcelerator is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

#
# Plugin Rakefile
#

require 'rake'
require 'fileutils'
require 'zip/zip'
require 'yaml'
require 'find'
require 'pathname'

NAME = 'java_spring'
ZIPFILE = File.expand_path "#{NAME}.zip"

desc 'default build which makes the plugin'
task :default => [:zip] do

end

desc 'zip up the plugin'
task :zip do
  src_dir = File.expand_path "#{File.dirname(__FILE__)}/src"
  etc_dir = File.expand_path "#{File.dirname(__FILE__)}/etc"
  templates_dir = File.expand_path "#{File.dirname(__FILE__)}/templates"
  FileUtils.rm_r ZIPFILE if File.exists? ZIPFILE
  Zip::ZipFile.open(ZIPFILE, Zip::ZipFile::CREATE) do |zipfile|
    [etc_dir,templates_dir].each do |dir|
      Find.find(dir) do |path|
          pathname = Pathname.new(path)
          if not path.include? '.svn' and pathname.file?
            filename = pathname.relative_path_from(Pathname.new(dir))
            name=path.gsub(File.dirname(__FILE__)+'/','')
            zipfile.add(name,dir+'/'+filename)
          end
      end 
    end
    Find.find(src_dir) do |path|
        pathname = Pathname.new(path)
        if not path.include? '.svn' and pathname.file?
          filename = pathname.relative_path_from(Pathname.new(src_dir))
          zipfile.add(filename,src_dir+'/'+filename)
        end
    end
    zipfile.add('build.yml','build.yml')
    zipfile.add('spring_license.txt','spring_license.txt')
    zipfile.add('spring_notice.txt','spring_notice.txt')
  end
end

desc 'install the plugin'
task :install => [:zip] do
  system "appcelerator install:plugin #{ZIPFILE}"
end

desc 'release the plugin'
task :release => [:zip] do
  system "appcelerator release:plugin #{ZIPFILE}"
end


