--- 
:type: widget
:name: app:security
:version: 1.0
:dependencies: 
- :type: websdk
  :version: ">=2.1"
  :name: websdk
:tags: [ security ]
:licenses: [6]
:description: "app:security is a simple widget which will attempt to hide content based on a security policy"