--- 
:type: widget
:name: app:pagination
:version: 1.0.2
:dependencies: 
- :type: websdk
  :version: ">=2.1.2"
  :name: websdk
:tags: [ pagination ]
:licenses: [4]
:description: "app:pagination is a control for assisting in pagination capabilities using messages"
