#
# This file is part of Appcelerator.
#
# Copyright (C) 2006-2008 by Appcelerator, Inc. All Rights Reserved.
# For more information, please visit http://www.appcelerator.org
#
# Appcelerator is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

def path(*args) File.expand_path(*args) end
struts_service_dir = File.dirname(__FILE__)
java_service_dir = path("../java", struts_service_dir)

require path("#{struts_service_dir}/../../build.rb")
require path("common.rb", java_service_dir)

config = load_config(struts_service_dir)
java_config = load_config(java_service_dir)

desc 'default struts build'

task :default do
  struts_stage_dir = path("struts", STAGE_DIR)
  java_build_dir = path("classes", struts_stage_dir)
  app_source = path("src", java_service_dir)
  app_struts_source = path("src", struts_service_dir)

  lib_dir = path("lib", struts_service_dir) # necessary to build -struts.jar
 
  clean_dir(struts_stage_dir)
  FileUtils.mkdir_p to_path(java_build_dir) 

  # build the latest appcelerator.jar for this release
  java_cp_dir = path("lib", java_service_dir)
  compile_dir(app_source, java_build_dir, java_cp_dir)
  app_jar_file = path("appcelerator-#{java_config[:version]}.jar", lib_dir)
  create_jar(app_jar_file, java_build_dir)

  # clean
  clean_dir(struts_stage_dir)
  FileUtils.mkdir_p to_path(java_build_dir) 

  # now create an appcelerator-struts.jar file
  compile_dir(app_struts_source, java_build_dir, [java_cp_dir, lib_dir])
  struts_jar_file = path("appcelerator-struts-#{config[:version]}.jar", lib_dir)
  create_jar(struts_jar_file, java_build_dir)

  zipfile = path("service_struts_#{config[:version]}.zip", STAGE_DIR)
  FileUtils.rm_rf zipfile
  Zip::ZipFile.open(zipfile, Zip::ZipFile::CREATE) do |zipfile|

    dist_dir = path('dist', struts_service_dir) 
    dofiles(dist_dir) do |f|
      if not f == '.'
        zipfile.add("dist/#{f}", "#{dist_dir}/#{f}")
      end
    end

    dofiles(lib_dir) do |f|
      if not f == '.'
        zipfile.add("dist/public/WEB-INF/lib/#{File.basename(f)}", "#{lib_dir}/#{f}")
      end
    end

    Dir["#{java_cp_dir}/**/*.jar"].each { |f|
        zipfile.add("dist/public/WEB-INF/lib/#{File.basename(f)}", f)
    }

    zipfile.add("build.yml", "build.yml")
    zipfile.add("install.rb", "install.rb")
  end

  # do some cleanup
  FileUtils.rm_rf(app_jar_file)
  FileUtils.rm_rf(struts_jar_file)
  FileUtils.rm_rf(struts_stage_dir)
end

