--- 
:type: widget
:name: app:field
:version: 1.0.3
:dependencies: 
- :type: websdk
  :version: ">=2.1.2"
  :name: websdk
:tags: [ uicontrol ]
:licenses: [4]
:description: "app:field is a ui control that supports laying out different types of fields for collecting or displaying values"
