--- 
:type: widget
:name: app:field
:version: 1.0.2
:dependencies: 
- :type: websdk
  :version: ">=2.1.2"
  :name: websdk
:tags: [ uicontrol ]
:description: "app:field is a ui control that supports laying out different types of fields for collecting or displaying values"
