---
:type: widget
:name: app:mp3player
:version: '1.2'
:dependencies:
- :type: websdk
  :version: ">=2.1"
  :name: websdk
:tags: [ audio, mp3, flash ]
:licenses: [1]
:description: "app:mp3player is a flash based mp3 player"
