require 'rubygems'
require 'hoe'
require './lib/appcelerator.rb'

Hoe.new('appcelerator', Appcelerator::VERSION) do |p|
  p.name = 'appcelerator'
  p.rubyforge_name = 'appcelerator'
  p.author = 'Appcelerator and contributors'
  p.email = 'info@appcelerator.org'
  p.summary = 'Appcelerator is an RIA framework for use with Ruby on Rails'
  p.description = p.paragraphs_of('README.txt', 2..5).join("\n\n")
  p.url = "http://www.appcelerator.org" 
  p.changes = p.paragraphs_of('History.txt', 0..1).join("\n\n")
  p.remote_rdoc_dir = '' # Release to root
  p.rsync_args << ' --exclude=statsvn/'
end
