--- 
:tags: [ sound ]

:type: widget
:release_notes: initial release
:licenses: [6]

:name: app:music_player
:dependencies: 
- :type: websdk
  :name: websdk
  :version: ">=2.1"
:version: 1.0
:description: app:music_player widget that supports streaming music and dynamically controlling the streaming like volume, pan, starting and stopping
