application: __projectname__
version: 1
runtime: python
api_version: 1


handlers:
- url: /servicebroker.*
  script: launch/servicebroker.py
- url: /proxy.*
  script: launch/proxy.py
- url: /
  static_files: public/index.html
  upload: public/index.html
- url: /
  static_dir: public/
