#
#
# This file is part of Appcelerator.
#
# Copyright 2006-2008 Appcelerator, Inc.
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#
BUILD_DIR = "#{File.dirname(__FILE__)}"

require File.expand_path("#{BUILD_DIR}/../build.rb")


task :all do
  build_subdir BUILD_DIR
end

task :java do
  FileUtils.cd("#{BUILD_DIR}/java") do |d|
    system "rake"
  end
end

task :python do
  FileUtils.cd("#{BUILD_DIR}/python") do |d|
    system "rake"
  end
end

task :appengine do
  FileUtils.cd("#{BUILD_DIR}/appengine") do |d|
    system "rake"
  end
end

task :dotnet do
  FileUtils.cd("#{BUILD_DIR}/dotnet") do |d|
    system "rake"
  end
end

task :ruby do
  FileUtils.cd("#{BUILD_DIR}/ruby") do |d|
    system "rake"
  end
end

task :perl do
  FileUtils.cd("#{BUILD_DIR}/perl") do |d|
    system "rake"
  end
end

task :php do
  FileUtils.cd("#{BUILD_DIR}/php") do |d|
    system "rake"
  end
end

task :zend do
  FileUtils.cd("#{BUILD_DIR}/zend") do |d|
    system "rake"
  end
end

task :merb do
  FileUtils.cd("#{BUILD_DIR}/merb") do |d|
    system "rake"
  end
end

task :mule do
  FileUtils.cd("#{BUILD_DIR}/mule") do |d|
    system "rake"
  end
end

task :struts do
  FileUtils.cd("#{BUILD_DIR}/struts") do |d|
    system "rake"
  end
end
