#
#
# This file is part of Appcelerator.
#
# Copyright (c) 2006-2008, Appcelerator, Inc.
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
# 
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
# 
#     * Redistributions in binary form must reproduce the above copyright notice,
#       this list of conditions and the following disclaimer in the documentation
#       and/or other materials provided with the distribution.
# 
#     * Neither the name of Appcelerator, Inc. nor the names of its
#       contributors may be used to endorse or promote products derived from this
#       software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
BUILD_DIR = "#{File.dirname(__FILE__)}"

require File.expand_path("#{BUILD_DIR}/../build.rb")


task :all do
  build_subdir BUILD_DIR
end

task :java do
  FileUtils.cd("#{BUILD_DIR}/java") do |d|
    system "rake"
  end
end

task :python do
  FileUtils.cd("#{BUILD_DIR}/python") do |d|
    system "rake"
  end
end

task :appengine do
  FileUtils.cd("#{BUILD_DIR}/appengine") do |d|
    system "rake"
  end
end

task :dotnet do
  FileUtils.cd("#{BUILD_DIR}/dotnet") do |d|
    system "rake"
  end
end

task :ruby do
  FileUtils.cd("#{BUILD_DIR}/ruby") do |d|
    system "rake"
  end
end

task :perl do
  FileUtils.cd("#{BUILD_DIR}/perl") do |d|
    system "rake"
  end
end

task :php do
  FileUtils.cd("#{BUILD_DIR}/php") do |d|
    system "rake"
  end
end

task :zend do
  FileUtils.cd("#{BUILD_DIR}/zend") do |d|
    system "rake"
  end
end

task :merb do
  FileUtils.cd("#{BUILD_DIR}/merb") do |d|
    system "rake"
  end
end
