#
# This file is part of Appcelerator.
#
# Copyright (C) 2006-2008 by Appcelerator, Inc. All Rights Reserved.
# For more information, please visit http://www.appcelerator.org
#
# Appcelerator is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
BUILD_DIR = "#{File.dirname(__FILE__)}"

require File.expand_path("#{BUILD_DIR}/../build.rb")


task :all do
  build_subdir BUILD_DIR
end

task :java do
  FileUtils.cd("#{BUILD_DIR}/java") do |d|
    system "rake"
  end
end

task :python do
  FileUtils.cd("#{BUILD_DIR}/python") do |d|
    system "rake"
  end
end

task :appengine do
  FileUtils.cd("#{BUILD_DIR}/pyappengine") do |d|
    system "rake"
  end
end

task :dotnet do
  FileUtils.cd("#{BUILD_DIR}/dotnet") do |d|
    system "rake"
  end
end

task :ruby do
  FileUtils.cd("#{BUILD_DIR}/ruby") do |d|
    system "rake"
  end
end

task :perl do
  FileUtils.cd("#{BUILD_DIR}/perl") do |d|
    system "rake"
  end
end

task :php do
  FileUtils.cd("#{BUILD_DIR}/php") do |d|
    system "rake"
  end
end

task :zend do
  FileUtils.cd("#{BUILD_DIR}/zend") do |d|
    system "rake"
  end
end

task :merb do
  FileUtils.cd("#{BUILD_DIR}/merb") do |d|
    system "rake"
  end
end
