--- 
:type: widget
:name: app:tabpanel
:version: 1.0.3
:dependencies: 
- :type: websdk
  :version: ">=2.1"
  :name: websdk
:tags: [ uicontrol, layout ]
:description: "app:tabpanel is a UI control for displaying content in tabs"