--- 
:type: widget
:name: app:imagetransition
:version: 1.0.2
:dependencies: 
- :type: websdk
  :version: ">=2.1"
  :name: websdk
:tags: [ images ]
:description: "app:imagetransition is a control for transition from one image to another"
