--- 
:dependencies: 
- :type: websdk
  :version: ">=2.1.1"
  :name: websdk
:type: widget
:version: 1.0
:description: ExtJS Grid Panel  
:name: app:ext_grid
:tags: [ extjs, grid, layout ]

:release_notes: initial release
:license: [1] 

