#
#
# This file is part of Appcelerator.
#
# Copyright (c) 2006-2008, Appcelerator, Inc.
# All rights reserved.
# 
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
# 
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
# 
#     * Redistributions in binary form must reproduce the above copyright notice,
#       this list of conditions and the following disclaimer in the documentation
#       and/or other materials provided with the distribution.
# 
#     * Neither the name of Appcelerator, Inc. nor the names of its
#       contributors may be used to endorse or promote products derived from this
#       software without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
# ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
# ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#

BUILD_DIR = "#{File.dirname(__FILE__)}" 
require File.expand_path("#{BUILD_DIR}/../../build.rb")
build_config = load_config(BUILD_DIR)

desc 'default google-appengine-python build'
task :default do

  FileUtils.mkdir_p "#{STAGE_DIR}"
  zipfile = "#{STAGE_DIR}/service_appengine_#{build_config[:version]}.zip"
  FileUtils.rm_rf zipfile
  
  src_dir = "#{BUILD_DIR}/src"
  lib_dir = "#{BUILD_DIR}/lib"
  py_dir  = "#{BUILD_DIR}/../python/src/module/appcelerator"
  
  Zip::ZipFile.open(zipfile, Zip::ZipFile::CREATE) do |zipfile|
    
    dofiles(src_dir) do |f|
      filename = f.to_s
      next if File.basename(filename[0,1]) == '.'
      zipfile.add("project/#{filename}","#{src_dir}/#{filename}")
    end
    
    dofiles(lib_dir) do |f|
      filename = f.to_s
      next if File.basename(filename[0,1]) == '.'
      zipfile.add("project/#{filename}","#{lib_dir}/#{filename}")
    end
    
    dofiles(py_dir) do |f|
      filename = f.to_s
      next if File.basename(filename[0,1]) == '.'
      zipfile.add("project/appcelerator/#{filename}","#{py_dir}/#{filename}")
    end
    
    Dir["#{BUILD_DIR}/installer/plugins/*.rb"].each do |fpath|
      filename = File.basename(fpath)
      next if filename[0,1] == '.'
      zipfile.add("plugins/#{filename}",fpath)
    end
    
    zipfile.add('plugins/python_config.rb', "#{BUILD_DIR}/../python/installer/python_config.rb")
    zipfile.add('install.rb', "#{BUILD_DIR}/installer/install.rb")
    zipfile.add('build.yml',"#{BUILD_DIR}/build.yml")
  end
end

